### ISSUE TITLE
MacOS with Qt installation framework - Please test

### ISSUE THREAD

**Issue by norulz** [opengribs/XyGrib#116]
A prerelease of version 1.1.2 is out in MacOS version. 
This is with the new installer frame work using an online repository.
Please test the installation and the application.
Also please try the XyGribMaintenanceTool.

@nohal @theeko74 and other Mac users - please give it a run.

**Comment by nohal** [comment]
Generally works. Just 2 notes
- The UX is totally non-Mac
- Installs to `~/Applications/XyGrib`, that is not normal on macOS (Actually I have exactly 0 other applications installed there)

**Comment by nohal** [comment]
The maintenance tool:
- Add/remove components dialog, unlike the installer, does not contain the high-res basemap.
- Update components fails with "Cannot retrieve remote tree No package sources set for this application."

**Comment by nohal** [comment]
After uninstallation, it is impossible to install again - the installer fails on the first Next button click with "Cannot retrieve remote tree"

**Comment by nohal** [comment]
And one note - some people are not very happy about the online installers as they like to transport the apps on pendrives and such to machines without internet access.
While technically a not a serious issue on macOS as the application bundle is self-contained so decently packaged applications are easy to copy even after the installation, not everybody knows it.

**Comment by norulz** [comment]
I replaced the repository a few minutes ago - that may be the "Cannot retrieve the remote tree"

There will be a second installer for offline installs. If online takes from the repository and if not from its own payload

I can change the install folder to /Applications/XyGrib

**Comment by norulz** [comment]
Made the changes and posted the Offline installer.

**Comment by norulz** [comment]
Going sailing tomorrow

![image](https://user-images.githubusercontent.com/6072089/46376553-f1489b80-c69e-11e8-88d9-9b7003090071.png)

**Comment by nohal** [comment]
Still waiting for spring here...
The new build is much better, pretty much all that's left is the weird feeling the Qt installer framework has on macOS. But there's not much that could be done about, maybe except changing the geometry that obviously comes from the windows installer to something more in line with the UI (Like the Qt installer here)
<img width="622" alt="screen shot 2018-10-02 at 18 16 15" src="https://user-images.githubusercontent.com/249856/46377571-55536b80-c66f-11e8-928e-6d47c1f2b969.png">

And I would probably offer force-closing the main-app before starting the maintenance tool instead of the current warning that gets immediately covered by the tool's window.

**Comment by norulz** [comment]
Currently only the width can be set in the config.xml file. I set this to 620 px. This to support seeing the table that shows up when the maintenance tool is run in the add/remove mode. The table shows current versions and dates.

I agree that the suggestion to close XyGrib should come before launching the tool. I'll get to it.
