### ISSUE TITLE
downloading the wrong area.

### ISSUE THREAD

**Issue by did-g** [opengribs/XyGrib#183]
Hi,
@norulz 
In commit 4ddd5abb06281bb81c741fdbf28511c7d7f08b08 
    Implemented Arome 0.025° regional model

Do you remember the reason for

```
--- a/src/MainWindow.cpp
+++ b/src/MainWindow.cpp
@@ -1466,6 +1466,12 @@ void MainWindow::slotFile_Load_GRIB ()
                 || terre->getGribFileRectangle (&x0,&y0, &x1,&y1) )
     {
 //        DBG("Rect is: %f, %f,   %f, %f", x0, y0, x1, y1);
+
+        if ( x0 > 180.0)
+            x0 = x0 - 360.0;
+        if ( x1 > 180.0)
+            x1 = x1 -360.0;
+
         // open the grib download dialog
                QString fname = DialogLoadGRIB::getFile (networkManager, this, x0,y0,x1,y1);
 

```
It could be a conflict with another patch but with this change if I try to download south Pacific (missing Africa is another issue):
![download array_2019-01-21_18-51-14](https://user-images.githubusercontent.com/12138026/51491323-50e1c880-1dae-11e9-997c-fb286a0d7a9c.png)

I get
![bad_zone_2019-01-21_18-54-43](https://user-images.githubusercontent.com/12138026/51491358-6b1ba680-1dae-11e9-8669-351351da6171.png)

**Comment by norulz** [comment]
Hi,
The reason was to change the longitude coordinates fed to the dialogDownloadGRIB when the previous loaded grib had one or two of the longitude coordinates west of 0. In the case of  -10, 350 would be shown. This caused some problems with the server side verification that checks if a requested rectangle is in bounds or not (for regional models)

I see that the correction algorithm needs to take -180/180 into account.

Do you have a fix?

**Comment by did-g** [comment]
No I haven't.

**Comment by norulz** [comment]
fixed
