### ISSUE TITLE
Displaying Wave arrows if there's no height and no period.

### ISSUE THREAD

**Issue by did-g** [opengribs/XyGrib#207]
Hi, 
Sometime in grib there's triplets in light wind with a direction but no height and no period.
Currently Xygrib displays the arrow.
![MF](https://user-images.githubusercontent.com/12138026/56961270-a9fe8c80-6b53-11e9-95dc-1534fa5d14b9.png)
![openskiron](https://user-images.githubusercontent.com/12138026/56961271-aa972300-6b53-11e9-9607-4953b01e1aa2.png)
Saildoc (or WWW3 remove them).
![saildoc](https://user-images.githubusercontent.com/12138026/56961272-aa972300-6b53-11e9-875e-6d5d4f0a3b8f.png)

With arrows removed

![openskiron waves removed](https://user-images.githubusercontent.com/12138026/56961427-0feb1400-6b54-11e9-8143-0e19f6286f27.png)

Thoughts?

**Comment by norulz** [comment]
I think you have a good point.
With wind the display is definitive. If grib record has zero wind a zero symbol is shown. Wind has magnitude shown in the barb arrows
I feel that showing a wave arrow (that has no magnitude) when the height value is 0, is misleading.
Regarding WW3, I'm not sure that missing wave records are due to the model predicting zero height for wind waves. It may be an input data assimilation issue (satellite coverage etc.).

I feel OK with not showing a wave direction arrow for wind waves when the height value is zero. 

David

**Comment by KiwiMETOC** [comment]
There are three possible waves that can be displayed depending upon the dataset - wind waves (aka "sea"), swell, and combined sea and swell. Even with zero wind, there may still be swell so that a wave direction is possible if the displayed waves are either swell or combined sea and swell. In the screenshots "significant wave height" is displayed. Combined sea and swell is often, and incorrectly, labelled "significant wave height". In reality SWH is simply a means of expressing wave heights of any kind regardless of whether it is sea, swell, or combined sea and swell, and to make some sense of a wave train that comprises waves of varying heights. SWH is the mean height of the highest one third of the waves and corresponds roughly to what a human observer might say the wave height was.

**Comment by did-g** [comment]
I made a PR https://github.com/opengribs/XyGrib/pull/208

**Comment by norulz** [comment]
Swell and wind waves have direction, period and height
Combined sea, to the best of my knowledge,  has only height and it is expressed in terms of SWH (mean of highest third)

**Comment by did-g** [comment]
Hi,
In my understanding grib have period and direction for combined sea:

from https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_table4-2-10-0.shtml

> 3 | Significant Height of Combined Wind Waves and Swell | m | HTSGW
> 4 | Direction of Wind Waves | degree true | WVDIR
> 5 | Significant Height of Wind Waves | m | WVHGT
> 6 | Mean Period of Wind Waves | s | WVPER
> 7 | Direction of Swell Waves | degree true | SWDIR
> 8 | Significant Height of Swell Waves | m | SWELL
> 9 | Mean Period of Swell Waves | s | SWPER
> 10 | Primary Wave Direction | degree true | DIRPW
> 11 | Primary Wave Mean Period | s | PERPW
> 12 | Secondary Wave Direction | degree true | DIRSW
> 13 | Secondary Wave Mean Period | s | PERSW
> 14 | Direction of Combined Wind Waves and Swell | degree true | WWSDIR
> 15 | Mean Period of Combined Wind Waves and Swell | s | MWSPER
> 
 
And at least Meteo France have them

> wgrib2 2019-05-04T00:00:00Z:102H.grib
> 
> 1:0:d=2019050400:WWSDIR:mean sea level:102 hour fcst:
> 2:257227:d=2019050400:MWSPER:mean sea level:102 hour fcst:
> 3:522553:d=2019050400:HTSGW:mean sea level:102 hour fcst:

> 4:783583:d=2019050400:WVDIR:mean sea level:102 hour fcst:
> 5:1103867:d=2019050400:WVPER:mean sea level:102 hour fcst:
> 6:1415586:d=2019050400:WVHGT:mean sea level:102 hour fcst:
...
> 13:3656308:d=2019050400:SWDIR:mean sea level:102 hour fcst:
> 14:3957719:d=2019050400:SWPER:mean sea level:102 hour fcst:
> 15:4256222:d=2019050400:SWELL:mean sea level:102 hour fcst:
...

**Comment by norulz** [comment]
I took a look at Copernicus data sheets for the WAM model (run by HCMR).
The same values appear to be there too with slightly different naming schemes.
See: http://resources.marine.copernicus.eu/documents/PUM/CMEMS-MED-PUM-006-017.pdf

DWD wave data has

```
Wind:   wind direction at 10m above ground
Swell: mean direction
Wind sea: mean wave direction
Swell: mean period
Wind sea: mean period
Swell: significant wave height
Wind sea: significant wave height
Wind: wind speed at 10m above ground
Total wave spectrum: significant wave height
Swell: Peak wave period
Wind sea: Peak wave period
Total wave spectrum: Mean wave direction
Total wave spectrum: Energy“ wave period

```
I assume the last two give the total wave spectrum direction and period

I'm OK to go ahead with the changes and additions. It means 9 wave variable instead of the 7 today.
I will take care of adding the two additional variables to EWAM, GWAM and WW3 in the grib server

**Comment by norulz** [comment]
Hi,
The NOAA gribs for WW3 have the following:

```
david@dell01:~/temp$ wgrib2 -v multi_1.glo_30m.t06z.f009.grib2
1:0:d=2019050406:WIND Wind Speed [m/s]:surface:9 hour fcst:
2:182378:d=2019050406:WDIR Wind Direction (from Which Blowing) [degtrue]:surface:9 hour fcst:
3:440618:d=2019050406:UGRD U-Component Of Wind [m/s]:surface:9 hour fcst:
4:623713:d=2019050406:VGRD V-Component Of Wind [m/s]:surface:9 hour fcst:
5:807603:d=2019050406:HTSGW Significant Height Of Combined Wind Waves And Swell [m]:surface:9 hour fcst:
6:918239:d=2019050406:PERPW Primary Wave Mean Period [s]:surface:9 hour fcst:
7:1057772:d=2019050406:DIRPW Primary Wave Direction [deg]:surface:9 hour fcst:
8:1277171:d=2019050406:WVHGT Significant Height Of Wind Waves [m]:surface:9 hour fcst:
9:1375900:d=2019050406:SWELL Significant Height Of Swell Waves [m]:1 in sequence:9 hour fcst:
10:1507033:d=2019050406:SWELL Significant Height Of Swell Waves [m]:2 in sequence:9 hour fcst:
11:1621990:d=2019050406:WVPER Mean Period Of Wind Waves [s]:surface:9 hour fcst:
12:1734414:d=2019050406:SWPER Mean Period Of Swell Waves [s]:1 in sequence:9 hour fcst:
13:1889409:d=2019050406:SWPER Mean Period Of Swell Waves [s]:2 in sequence:9 hour fcst:
14:2050734:d=2019050406:WVDIR Direction Of Wind Waves [deg]:surface:9 hour fcst:
15:2212499:d=2019050406:SWDIR Direction Of Swell Waves [deg]:1 in sequence:9 hour fcst:
16:2449873:d=2019050406:SWDIR Direction Of Swell Waves [deg]:2 in sequence:9 hour fcst:

```
WWSDIR and MWSPER to not exist in these gribs.  It appears that we will need to use DIRPW and PERPW instead. The European DWD gribs have WWSDIR and MWSPER.

Do you feel that these variable are interchangeable?

**Comment by did-g** [comment]
Hi,
I'm not sure, for reference:
https://www.nco.ncep.noaa.gov/pmb/docs/grib2/GRIB2_parmeter_conversion_table.html

It should be testable with Brittany waves for  Sunday, wind and swell are 180°

Meteo France Arome + wave
http://grib-downloader.tk/POLAR/Brest-20190504-06.grb2
combined wind and swell (mostly swell from W)
![Capture d’écran_2019-05-04_14-20-14](https://user-images.githubusercontent.com/12138026/57178954-97989180-6e78-11e9-85da-8b7763ee8c25.png)
Same with wind:
![Capture d’écran_2019-05-04_14-19-43](https://user-images.githubusercontent.com/12138026/57178955-98312800-6e78-11e9-9104-d212e43232d9.png)

Xygrib download
![Capture d’écran_2019-05-04_14-18-39](https://user-images.githubusercontent.com/12138026/57178956-98312800-6e78-11e9-896b-08eca17890eb.png)


BTW: 
- it seems Xygrib downloader truncate wave bounding box.
- jpeg and simple encoding are using bitmap for wave and current, you can reduce the size with submsg, I've double checked and all viewers can read them. 
above wave only grib
wave.grb size 34 559  bytes
after
wgrib2 wave.grb -inv /dev/null -tosubmsg  wave-sub.grb
wave-sub.grb 17 757 bytes

**Comment by norulz** [comment]
Hi,

Not sure what it is that you wish to point out in https://www.nco.ncep.noaa.gov/pmb/docs/grib2/GRIB2_parmeter_conversion_table.html

There are often cases of wind 180 to swell. The swell arrives from a distant area where it could have been created by a different direction of wind.

The difference in cropping of the atmospheric grib and the WW3 grib is due to the difference in resolution. (0.25 deg vs 0.5 deg). The same bounding box coordinates are fed to wgrib2 -small_grib for both the atm and the wave gribs.

The use of submsg to reduce size is interesting and I'll give it a try later this week.

**Comment by did-g** [comment]
Hi,
at first Zygrib and NOAA were using grib1, this table show what they use when converting to grib2.
There's still a lot of GRIB1 logic in Xygrib. It's something to keep in mind when modifying it.

My point with the swell and wave being at 180 is that when double checking what WWW3 parameters are for is rather easy: wind, swell and sea (combined) have very different direction, not so easy when wind and swell are more or less the same.
 
Good point for bounding box and cropping. Maybe WW3 or whatever has the lower resolution should use a bigger box then? Speaking only for myself but as a user it's what I want.

Regards
Didier

**Comment by norulz** [comment]
ZyGrib also used FNMOC WW3 model's grib files. We are using NOAA's WW3 model. There are differences in the content.
The main issue is that WW3 does not provide the combined wind-wave and swell period and direction but that of the Primary wave, whereas the European models  use combined wind-wave & swell. I'm not sure if the two variants can be considered the same for practical purposes. I have a contact in NOAA and will try to get an explanation how they see the difference between the two.

We do need to decide if we keep and manage two sets of variables. One for WW3 and one for the other wave models

Bounding box: this is an internal logic inside wgrib2. It would be possible to have some fancy logic in the grib server script to adjust the user bounding box to get a better result. Alternately we could build a custom version of wgrib2. I'm not sure that it is worth the effort. :-)

**Comment by KiwiMETOC** [comment]
Looking at what the Bureau of Meteorology in Australia does "primary wave period" is also known as the "peak wave period", and likewise the wave direction. This is the result of spectral analysis of the total wave spectrum and thus should equate to "combined sea and swell". 
This quote, from http://www.bom.gov.au/nwp/doc/auswave/data.shtml, is interesting about what they do when there is no sea or no swell:
"The aim of spectral partitioning is to separate the wave spectrum into spectral components to represent distinct wave systems, such as wind sea and swell. The partitioning scheme within AUSWAVE is capable of separating the wave spectrum into a single wind sea component and multiple swell components. If no identified partition meets a threshold wind sea fraction at a given grid point, no wind sea will be present at that grid point. Likewise, if all the energy is assigned to wind sea, there will be no energy for the swell components. These 'holes' in the grid are consistent with the physical processes being described by the partitioning. They do not represent missing values."

**Comment by did-g** [comment]
@KiwiMETOC , interesting, thanks for the link.
More links:
WMO
https://library.wmo.int/doc_num.php?explnum_id=3110

ECMWF
https://www.ecmwf.int/sites/default/files/elibrary/2017/17739-part-vii-ecmwf-wave-model.pdf

WAVEWATCH III
https://raw.githubusercontent.com/wiki/NOAA-EMC/WW3/files/manual.pdf
