### ISSUE TITLE
Belgium opendata gribs

### ISSUE THREAD

**Issue by norulz** [opengribs/XyGrib#218]
Hi @did-g 

The grib1s at https://opendata.meteo.be/downloadPage.php do not open.
It appears that they are using table2Value of 228 which does not match ECMWF or anything else I know.
Do you have a clue on how to deal with this source of gribs?

**Comment by did-g** [comment]
Hi,

The same as we do with ECMWF ERA5 grib1 I guess. On the other hand Xygrib is unable to open and merge multiple files meaning user has to concatenate them before opening Xygrib.

**Comment by dominiquehausser** [comment]
It is nice for some data (temperature, humidity, pressure) but not for wind. Is  it because it is at 10 meters or because this the vertical or the horizontal component of the wind that make XyGrib unable to read data.

This give an error message for different data like rain or geopotential (see attached file)
![Capture d’écran de 2019-06-23 17-13-36](https://user-images.githubusercontent.com/38014738/59978209-471cf500-95da-11e9-9e84-8853140f0827.png)

**Comment by rgleason** [comment]
We've found opencpn grib_pi file concatenation very useful. Would it be difficult to improve  XYGrib this way?

**Comment by norulz** [comment]
Will appear in next release
