### ISSUE TITLE
Is there a command line API to download weather models via XyGrib?

### ISSUE THREAD

**Issue by meteoDaniel** [opengribs/XyGrib#251]
Dear all, 
I have seen that the XyGrib Gui is able to download forecast models. 
Is there a command line interface to trigger the downloads?
This would be a nice feature for me. 
Thanks for answering

**Comment by norulz** [comment]
Hi,
Sorry to disappoint but there is no published interface and we actually discourage scripted usage of the XyGrib grib server resources. This is due to quite limited cloud server resources needed for support the quite large demand via XyGrib and qtVlm.
All the gribs that are available in the grib server have been script downloaded from free and open sources and script "packaged" for the XyGrib grib server. It seems logical that if you need a scripted solution your best bet might be by using the same open data sources.
Best,
David

**Comment by MennoTammens** [comment]
Hi David,

Are the scripts to download and package the gribs available in an open source project?

Menno

**Comment by norulz** [comment]
Hi Menno,
They have not been posted. 
Pls contact me by email.
