### ISSUE TITLE
Next version - An open discussion

### ISSUE THREAD

**Issue by norulz** [opengribs/XyGrib#99]
The principle addition intended for next version (1.2.0) is to add 5 wide area regional models with resolutions near 0.1 degree (medium resolution). These will include:

- NAM Caribbean and Central America
- NAM Continental US
- NAM Hawai
- Arpege 0.1 (Europe)
- ICON-EU nest (Europe) 

New functionality needed:
To handle these non global models we will need to visually indicate to the user where the coverage of the selected model is. We also will need to ensure that the selection is not outside the coverage. This will need some graphic overlay. We will need to decide on the UI flow for this.

A second issue is map projection. NAM CONUS uses Lamberth Conformal instead of Lat/Lon. I prefer not to re-project in pre-processing for the grib server but to be able to handle as much as possible in native form.

What is the best way to handle this? Are there issues that I'm missing ? Please raise them

David

**Comment by dominiquehausser** [comment]
1. I would be interested to have the current / tide stream.
Probably the easiest one is RTOFS (NOAA), because through saildocs it is only to have data every 24h at 0000 UTC. For tides streams, it not enough ;-)
For Europe, I only know the precut files from IBI-MFC described in the french version of Grib sources, but not in the englih page - I'll modify that ASAP) (Courants de surfaces produits par Iberia-Biscay-Ireland Monitoring and Forecasting Centre (IBI-MFC) et disponibles entre autres sur MyOcean).
There is probably other sources, but I did not find them yet.

2. For the limitation, look how it was done for meteoblue in zyGrib, as it was limited around CH (a square of 100 or 200 or 300 km2). It was working well if request was larger to come back to the max size and it was possible to see the coverage of the data.

3. I am not sure that users will easily understand a map using Lambert Conformal Conic instead of Mercator, which means that even if you add the projection in the list of existing projections in XyGrib, you will have to calculate the map conversion and also convert the projection of the grib to allow a Mercator or other cylindric projection. In fact when looking on different web sites they always keep a cylindric projection and convert the grib projection.

**Comment by dominiquehausser** [comment]
There is also a need to separate data from application, not only in AppImage, but also when build and install from source, which probably need some work at the level of the code or may be at the level of cmake.

I suggest that the data are strored in /usr/local/share/openGribs/XyGrib as the primary folder for data and only modified files in $HOME/.config/openGribs/XyGrib, so it does not create multiple identical files in case of multiple users in a device.
